name: Generate Docs

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux

          - os: windows-latest
            platform: windows

          - os: macos-latest
            platform: darwin

    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Set up python.
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies.
        shell: bash
        run: |
          python -m pip install .

          if [ "$RUNNER_OS" == "macOS" ]; then
            install_name_tool -add_rpath /opt/homebrew/lib ./sdl3/bin/darwin-arm64/libSDL3_ttf.dylib
          fi

      - name: Generate docs.
        run: |
          python -c "import sdl3"

      - name: Upload asset.
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: sdl3/__doc__.py
          asset_name: ${{ matrix.platform }}-docs.py
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}