name: Deploy

on:
  workflow_run:
    workflows: ["Generate Docs"]
    types: [completed]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check workflow run conclusion.
        if: github.event.workflow_run.conclusion != 'success'
        run: exit 1

      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Set up Python.
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies.
        run: python -m pip install --upgrade pip build

      - name: Build package.
        run: python -m build

      - name: Publish package.
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{secrets.PYPI_API_TOKEN}}