name: Tests

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        system: [Linux, Darwin, Windows]
        version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

        include:
          - system: Linux
            os: ubuntu-latest

          - system: Darwin
            os: macos-latest

          - system: Windows
            os: windows-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Set up Python ${{matrix.version}}.
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.version}}

      - name: Install dependencies.
        shell: bash
        run: |
          python -m pip install .

          if [ "${{matrix.system}}" == "Darwin" ]; then
            echo "DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
          fi

      - name: Run tests.
        shell: bash
        run: |
          python -c "import sdl3"
        env:
          SDL_GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}