name: Tests

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest, windows-latest]
        version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Set up Python ${{matrix.version}}.
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.version}}

      - name: Install dependencies.
        shell: bash
        run: |
          python -m pip install .

      - name: Run tests.
        shell: bash
        run: |
          python -c "import sdl3"
        env:
          SDL_GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}