name: Tests

on:
  workflow_run:
    workflows: ["Generate Docs"]
    types: [completed]

  pull_request:
    branches: [main]

  push:
    branches: [main]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{matrix.os}}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-15, windows-2025]
        version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Set up Python ${{matrix.version}}.
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.version}}

      - name: Install dependencies.
        shell: bash
        run: python -m pip install .

      - name: Run tests.
        shell: bash
        run: python -c "import tests"
        env:
          SDL_DOC_GENERATOR: ${{github.event_name == 'workflow_run' && '1' || '0'}}
          SDL_GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}